services:
  - type: web
    name: sign-language-backend
    env: python
    plan: free
    buildCommand: pip install -r sign-language-backend/requirements.txt
    startCommand: python sign-language-backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
